// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: pkg/grpc/proto/cronicle.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CronicleService_RegisterNode_FullMethodName     = "/cronicle.CronicleService/RegisterNode"
	CronicleService_Heartbeat_FullMethodName        = "/cronicle.CronicleService/Heartbeat"
	CronicleService_UnregisterNode_FullMethodName   = "/cronicle.CronicleService/UnregisterNode"
	CronicleService_SubmitTask_FullMethodName       = "/cronicle.CronicleService/SubmitTask"
	CronicleService_StreamLogs_FullMethodName       = "/cronicle.CronicleService/StreamLogs"
	CronicleService_ReportTaskResult_FullMethodName = "/cronicle.CronicleService/ReportTaskResult"
	CronicleService_AbortTask_FullMethodName        = "/cronicle.CronicleService/AbortTask"
)

// CronicleServiceClient is the client API for CronicleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Master 与 Worker 之间的核心通信服务
type CronicleServiceClient interface {
	// Worker 向 Master 注册
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	// Worker 发送心跳
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Worker 下线通知
	UnregisterNode(ctx context.Context, in *UnregisterNodeRequest, opts ...grpc.CallOption) (*UnregisterNodeResponse, error)
	// Master 向 Worker 提交任务
	SubmitTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	// Worker 向 Master 流式传输日志
	StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogChunk, LogAck], error)
	// Worker 上报任务执行结果
	ReportTaskResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*TaskResultAck, error)
	// Master 中止任务
	AbortTask(ctx context.Context, in *AbortTaskRequest, opts ...grpc.CallOption) (*AbortTaskResponse, error)
}

type cronicleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCronicleServiceClient(cc grpc.ClientConnInterface) CronicleServiceClient {
	return &cronicleServiceClient{cc}
}

func (c *cronicleServiceClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, CronicleService_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronicleServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, CronicleService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronicleServiceClient) UnregisterNode(ctx context.Context, in *UnregisterNodeRequest, opts ...grpc.CallOption) (*UnregisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterNodeResponse)
	err := c.cc.Invoke(ctx, CronicleService_UnregisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronicleServiceClient) SubmitTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, CronicleService_SubmitTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronicleServiceClient) StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogChunk, LogAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CronicleService_ServiceDesc.Streams[0], CronicleService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogChunk, LogAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CronicleService_StreamLogsClient = grpc.ClientStreamingClient[LogChunk, LogAck]

func (c *cronicleServiceClient) ReportTaskResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*TaskResultAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResultAck)
	err := c.cc.Invoke(ctx, CronicleService_ReportTaskResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cronicleServiceClient) AbortTask(ctx context.Context, in *AbortTaskRequest, opts ...grpc.CallOption) (*AbortTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortTaskResponse)
	err := c.cc.Invoke(ctx, CronicleService_AbortTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CronicleServiceServer is the server API for CronicleService service.
// All implementations must embed UnimplementedCronicleServiceServer
// for forward compatibility.
//
// Master 与 Worker 之间的核心通信服务
type CronicleServiceServer interface {
	// Worker 向 Master 注册
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	// Worker 发送心跳
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Worker 下线通知
	UnregisterNode(context.Context, *UnregisterNodeRequest) (*UnregisterNodeResponse, error)
	// Master 向 Worker 提交任务
	SubmitTask(context.Context, *TaskRequest) (*TaskResponse, error)
	// Worker 向 Master 流式传输日志
	StreamLogs(grpc.ClientStreamingServer[LogChunk, LogAck]) error
	// Worker 上报任务执行结果
	ReportTaskResult(context.Context, *TaskResult) (*TaskResultAck, error)
	// Master 中止任务
	AbortTask(context.Context, *AbortTaskRequest) (*AbortTaskResponse, error)
	mustEmbedUnimplementedCronicleServiceServer()
}

// UnimplementedCronicleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCronicleServiceServer struct{}

func (UnimplementedCronicleServiceServer) RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedCronicleServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedCronicleServiceServer) UnregisterNode(context.Context, *UnregisterNodeRequest) (*UnregisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterNode not implemented")
}
func (UnimplementedCronicleServiceServer) SubmitTask(context.Context, *TaskRequest) (*TaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitTask not implemented")
}
func (UnimplementedCronicleServiceServer) StreamLogs(grpc.ClientStreamingServer[LogChunk, LogAck]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedCronicleServiceServer) ReportTaskResult(context.Context, *TaskResult) (*TaskResultAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportTaskResult not implemented")
}
func (UnimplementedCronicleServiceServer) AbortTask(context.Context, *AbortTaskRequest) (*AbortTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AbortTask not implemented")
}
func (UnimplementedCronicleServiceServer) mustEmbedUnimplementedCronicleServiceServer() {}
func (UnimplementedCronicleServiceServer) testEmbeddedByValue()                         {}

// UnsafeCronicleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CronicleServiceServer will
// result in compilation errors.
type UnsafeCronicleServiceServer interface {
	mustEmbedUnimplementedCronicleServiceServer()
}

func RegisterCronicleServiceServer(s grpc.ServiceRegistrar, srv CronicleServiceServer) {
	// If the following call panics, it indicates UnimplementedCronicleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CronicleService_ServiceDesc, srv)
}

func _CronicleService_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronicleServiceServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronicleService_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronicleServiceServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronicleService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronicleServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronicleService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronicleServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronicleService_UnregisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronicleServiceServer).UnregisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronicleService_UnregisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronicleServiceServer).UnregisterNode(ctx, req.(*UnregisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronicleService_SubmitTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronicleServiceServer).SubmitTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronicleService_SubmitTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronicleServiceServer).SubmitTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronicleService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CronicleServiceServer).StreamLogs(&grpc.GenericServerStream[LogChunk, LogAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CronicleService_StreamLogsServer = grpc.ClientStreamingServer[LogChunk, LogAck]

func _CronicleService_ReportTaskResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronicleServiceServer).ReportTaskResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronicleService_ReportTaskResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronicleServiceServer).ReportTaskResult(ctx, req.(*TaskResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _CronicleService_AbortTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronicleServiceServer).AbortTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CronicleService_AbortTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronicleServiceServer).AbortTask(ctx, req.(*AbortTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CronicleService_ServiceDesc is the grpc.ServiceDesc for CronicleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CronicleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cronicle.CronicleService",
	HandlerType: (*CronicleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _CronicleService_RegisterNode_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _CronicleService_Heartbeat_Handler,
		},
		{
			MethodName: "UnregisterNode",
			Handler:    _CronicleService_UnregisterNode_Handler,
		},
		{
			MethodName: "SubmitTask",
			Handler:    _CronicleService_SubmitTask_Handler,
		},
		{
			MethodName: "ReportTaskResult",
			Handler:    _CronicleService_ReportTaskResult_Handler,
		},
		{
			MethodName: "AbortTask",
			Handler:    _CronicleService_AbortTask_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _CronicleService_StreamLogs_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/grpc/proto/cronicle.proto",
}
