// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: cronicle.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskType int32

const (
	TaskType_SHELL  TaskType = 0
	TaskType_HTTP   TaskType = 1
	TaskType_DOCKER TaskType = 2
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "SHELL",
		1: "HTTP",
		2: "DOCKER",
	}
	TaskType_value = map[string]int32{
		"SHELL":  0,
		"HTTP":   1,
		"DOCKER": 2,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_cronicle_proto_enumTypes[0].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_cronicle_proto_enumTypes[0]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_cronicle_proto_rawDescGZIP(), []int{0}
}

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Resources     *NodeResources         `protobuf:"bytes,4,opt,name=resources,proto3" json:"resources,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	GrpcAddress   string                 `protobuf:"bytes,6,opt,name=grpc_address,json=grpcAddress,proto3" json:"grpc_address,omitempty"` // Worker executor gRPC 服务地址（格式：host:port）
	Pid           int32                  `protobuf:"varint,7,opt,name=pid,proto3" json:"pid,omitempty"`                                   // Worker 进程 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_cronicle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cronicle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_cronicle_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterNodeRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterNodeRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RegisterNodeRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RegisterNodeRequest) GetResources() *NodeResources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *RegisterNodeRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterNodeRequest) GetGrpcAddress() string {
	if x != nil {
		return x.GrpcAddress
	}
	return ""
}

func (x *RegisterNodeRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	SecurityToken string                 `protobuf:"bytes,4,opt,name=security_token,json=securityToken,proto3" json:"security_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_cronicle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cronicle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_cronicle_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterNodeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterNodeResponse) GetSecurityToken() string {
	if x != nil {
		return x.SecurityToken
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Resources     *NodeResources         `protobuf:"bytes,2,opt,name=resources,proto3" json:"resources,omitempty"`
	RunningJobs   []string               `protobuf:"bytes,3,rep,name=running_jobs,json=runningJobs,proto3" json:"running_jobs,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_cronicle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cronicle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_cronicle_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetResources() *NodeResources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *HeartbeatRequest) GetRunningJobs() []string {
	if x != nil {
		return x.RunningJobs
	}
	return nil
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_cronicle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cronicle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_cronicle_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type UnregisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterNodeRequest) Reset() {
	*x = UnregisterNodeRequest{}
	mi := &file_cronicle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterNodeRequest) ProtoMessage() {}

func (x *UnregisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cronicle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterNodeRequest.ProtoReflect.Descriptor instead.
func (*UnregisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_cronicle_proto_rawDescGZIP(), []int{4}
}

func (x *UnregisterNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type UnregisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterNodeResponse) Reset() {
	*x = UnregisterNodeResponse{}
	mi := &file_cronicle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterNodeResponse) ProtoMessage() {}

func (x *UnregisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cronicle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterNodeResponse.ProtoReflect.Descriptor instead.
func (*UnregisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_cronicle_proto_rawDescGZIP(), []int{5}
}

func (x *UnregisterNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnregisterNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Type          TaskType               `protobuf:"varint,3,opt,name=type,proto3,enum=cronicle.TaskType" json:"type,omitempty"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Env           map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timeout       int32                  `protobuf:"varint,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	WorkingDir    string                 `protobuf:"bytes,7,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	ScheduledTime int64                  `protobuf:"varint,8,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"`
	StrictMode    bool                   `protobuf:"varint,9,opt,name=strict_mode,json=strictMode,proto3" json:"strict_mode,omitempty"` // 严格模式：任何命令失败立即退出
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_cronicle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cronicle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_cronicle_proto_rawDescGZIP(), []int{6}
}

func (x *TaskRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TaskRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *TaskRequest) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_SHELL
}

func (x *TaskRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *TaskRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *TaskRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *TaskRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *TaskRequest) GetScheduledTime() int64 {
	if x != nil {
		return x.ScheduledTime
	}
	return 0
}

func (x *TaskRequest) GetStrictMode() bool {
	if x != nil {
		return x.StrictMode
	}
	return false
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_cronicle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cronicle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_cronicle_proto_rawDescGZIP(), []int{7}
}

func (x *TaskResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *TaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	ResourceUsage *ResourceUsage         `protobuf:"bytes,6,opt,name=resource_usage,json=resourceUsage,proto3" json:"resource_usage,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_cronicle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_cronicle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_cronicle_proto_rawDescGZIP(), []int{8}
}

func (x *TaskResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TaskResult) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *TaskResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TaskResult) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TaskResult) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *TaskResult) GetResourceUsage() *ResourceUsage {
	if x != nil {
		return x.ResourceUsage
	}
	return nil
}

func (x *TaskResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type TaskResultAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResultAck) Reset() {
	*x = TaskResultAck{}
	mi := &file_cronicle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResultAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResultAck) ProtoMessage() {}

func (x *TaskResultAck) ProtoReflect() protoreflect.Message {
	mi := &file_cronicle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResultAck.ProtoReflect.Descriptor instead.
func (*TaskResultAck) Descriptor() ([]byte, []int) {
	return file_cronicle_proto_rawDescGZIP(), []int{9}
}

func (x *TaskResultAck) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

type AbortTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortTaskRequest) Reset() {
	*x = AbortTaskRequest{}
	mi := &file_cronicle_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortTaskRequest) ProtoMessage() {}

func (x *AbortTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cronicle_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortTaskRequest.ProtoReflect.Descriptor instead.
func (*AbortTaskRequest) Descriptor() ([]byte, []int) {
	return file_cronicle_proto_rawDescGZIP(), []int{10}
}

func (x *AbortTaskRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AbortTaskRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AbortTaskRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AbortTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortTaskResponse) Reset() {
	*x = AbortTaskResponse{}
	mi := &file_cronicle_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortTaskResponse) ProtoMessage() {}

func (x *AbortTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cronicle_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortTaskResponse.ProtoReflect.Descriptor instead.
func (*AbortTaskResponse) Descriptor() ([]byte, []int) {
	return file_cronicle_proto_rawDescGZIP(), []int{11}
}

func (x *AbortTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AbortTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NodeResources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage      float64                `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   float64                `protobuf:"fixed64,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	MemoryTotal   float64                `protobuf:"fixed64,3,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	DiskUsage     float64                `protobuf:"fixed64,4,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	DiskTotal     float64                `protobuf:"fixed64,5,opt,name=disk_total,json=diskTotal,proto3" json:"disk_total,omitempty"`
	CpuCores      int32                  `protobuf:"varint,6,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeResources) Reset() {
	*x = NodeResources{}
	mi := &file_cronicle_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeResources) ProtoMessage() {}

func (x *NodeResources) ProtoReflect() protoreflect.Message {
	mi := &file_cronicle_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeResources.ProtoReflect.Descriptor instead.
func (*NodeResources) Descriptor() ([]byte, []int) {
	return file_cronicle_proto_rawDescGZIP(), []int{12}
}

func (x *NodeResources) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *NodeResources) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *NodeResources) GetMemoryTotal() float64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *NodeResources) GetDiskUsage() float64 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *NodeResources) GetDiskTotal() float64 {
	if x != nil {
		return x.DiskTotal
	}
	return 0
}

func (x *NodeResources) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

type ResourceUsage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent     float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryBytes    int64                  `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	ElapsedSeconds float64                `protobuf:"fixed64,3,opt,name=elapsed_seconds,json=elapsedSeconds,proto3" json:"elapsed_seconds,omitempty"`
	CpuCores       int32                  `protobuf:"varint,4,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryTotal    int64                  `protobuf:"varint,5,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResourceUsage) Reset() {
	*x = ResourceUsage{}
	mi := &file_cronicle_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUsage) ProtoMessage() {}

func (x *ResourceUsage) ProtoReflect() protoreflect.Message {
	mi := &file_cronicle_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUsage.ProtoReflect.Descriptor instead.
func (*ResourceUsage) Descriptor() ([]byte, []int) {
	return file_cronicle_proto_rawDescGZIP(), []int{13}
}

func (x *ResourceUsage) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ResourceUsage) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ResourceUsage) GetElapsedSeconds() float64 {
	if x != nil {
		return x.ElapsedSeconds
	}
	return 0
}

func (x *ResourceUsage) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *ResourceUsage) GetMemoryTotal() int64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

var File_cronicle_proto protoreflect.FileDescriptor

const file_cronicle_proto_rawDesc = "" +
	"\n" +
	"\x0ecronicle.proto\x12\bcronicle\"\xdb\x01\n" +
	"\x13RegisterNodeRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x125\n" +
	"\tresources\x18\x04 \x01(\v2\x17.cronicle.NodeResourcesR\tresources\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12!\n" +
	"\fgrpc_address\x18\x06 \x01(\tR\vgrpcAddress\x12\x10\n" +
	"\x03pid\x18\a \x01(\x05R\x03pid\"\x8a\x01\n" +
	"\x14RegisterNodeResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12%\n" +
	"\x0esecurity_token\x18\x04 \x01(\tR\rsecurityToken\"\xa3\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x125\n" +
	"\tresources\x18\x02 \x01(\v2\x17.cronicle.NodeResourcesR\tresources\x12!\n" +
	"\frunning_jobs\x18\x03 \x03(\tR\vrunningJobs\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"N\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\"0\n" +
	"\x15UnregisterNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"L\n" +
	"\x16UnregisterNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xee\x02\n" +
	"\vTaskRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12&\n" +
	"\x04type\x18\x03 \x01(\x0e2\x12.cronicle.TaskTypeR\x04type\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x120\n" +
	"\x03env\x18\x05 \x03(\v2\x1e.cronicle.TaskRequest.EnvEntryR\x03env\x12\x18\n" +
	"\atimeout\x18\x06 \x01(\x05R\atimeout\x12\x1f\n" +
	"\vworking_dir\x18\a \x01(\tR\n" +
	"workingDir\x12%\n" +
	"\x0escheduled_time\x18\b \x01(\x03R\rscheduledTime\x12\x1f\n" +
	"\vstrict_mode\x18\t \x01(\bR\n" +
	"strictMode\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\fTaskResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xfa\x01\n" +
	"\n" +
	"TaskResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12>\n" +
	"\x0eresource_usage\x18\x06 \x01(\v2\x17.cronicle.ResourceUsageR\rresourceUsage\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\"+\n" +
	"\rTaskResultAck\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\"\\\n" +
	"\x10AbortTaskRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"G\n" +
	"\x11AbortTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xcd\x01\n" +
	"\rNodeResources\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x02 \x01(\x01R\vmemoryUsage\x12!\n" +
	"\fmemory_total\x18\x03 \x01(\x01R\vmemoryTotal\x12\x1d\n" +
	"\n" +
	"disk_usage\x18\x04 \x01(\x01R\tdiskUsage\x12\x1d\n" +
	"\n" +
	"disk_total\x18\x05 \x01(\x01R\tdiskTotal\x12\x1b\n" +
	"\tcpu_cores\x18\x06 \x01(\x05R\bcpuCores\"\xbc\x01\n" +
	"\rResourceUsage\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\x12'\n" +
	"\x0felapsed_seconds\x18\x03 \x01(\x01R\x0eelapsedSeconds\x12\x1b\n" +
	"\tcpu_cores\x18\x04 \x01(\x05R\bcpuCores\x12!\n" +
	"\fmemory_total\x18\x05 \x01(\x03R\vmemoryTotal*+\n" +
	"\bTaskType\x12\t\n" +
	"\x05SHELL\x10\x00\x12\b\n" +
	"\x04HTTP\x10\x01\x12\n" +
	"\n" +
	"\x06DOCKER\x10\x022\xc1\x03\n" +
	"\x0fCronicleService\x12M\n" +
	"\fRegisterNode\x12\x1d.cronicle.RegisterNodeRequest\x1a\x1e.cronicle.RegisterNodeResponse\x12D\n" +
	"\tHeartbeat\x12\x1a.cronicle.HeartbeatRequest\x1a\x1b.cronicle.HeartbeatResponse\x12S\n" +
	"\x0eUnregisterNode\x12\x1f.cronicle.UnregisterNodeRequest\x1a .cronicle.UnregisterNodeResponse\x12;\n" +
	"\n" +
	"SubmitTask\x12\x15.cronicle.TaskRequest\x1a\x16.cronicle.TaskResponse\x12A\n" +
	"\x10ReportTaskResult\x12\x14.cronicle.TaskResult\x1a\x17.cronicle.TaskResultAck\x12D\n" +
	"\tAbortTask\x12\x1a.cronicle.AbortTaskRequest\x1a\x1b.cronicle.AbortTaskResponseB/Z-github.com/cronicle/cronicle-next/pkg/grpc/pbb\x06proto3"

var (
	file_cronicle_proto_rawDescOnce sync.Once
	file_cronicle_proto_rawDescData []byte
)

func file_cronicle_proto_rawDescGZIP() []byte {
	file_cronicle_proto_rawDescOnce.Do(func() {
		file_cronicle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cronicle_proto_rawDesc), len(file_cronicle_proto_rawDesc)))
	})
	return file_cronicle_proto_rawDescData
}

var file_cronicle_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cronicle_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_cronicle_proto_goTypes = []any{
	(TaskType)(0),                  // 0: cronicle.TaskType
	(*RegisterNodeRequest)(nil),    // 1: cronicle.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),   // 2: cronicle.RegisterNodeResponse
	(*HeartbeatRequest)(nil),       // 3: cronicle.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 4: cronicle.HeartbeatResponse
	(*UnregisterNodeRequest)(nil),  // 5: cronicle.UnregisterNodeRequest
	(*UnregisterNodeResponse)(nil), // 6: cronicle.UnregisterNodeResponse
	(*TaskRequest)(nil),            // 7: cronicle.TaskRequest
	(*TaskResponse)(nil),           // 8: cronicle.TaskResponse
	(*TaskResult)(nil),             // 9: cronicle.TaskResult
	(*TaskResultAck)(nil),          // 10: cronicle.TaskResultAck
	(*AbortTaskRequest)(nil),       // 11: cronicle.AbortTaskRequest
	(*AbortTaskResponse)(nil),      // 12: cronicle.AbortTaskResponse
	(*NodeResources)(nil),          // 13: cronicle.NodeResources
	(*ResourceUsage)(nil),          // 14: cronicle.ResourceUsage
	nil,                            // 15: cronicle.TaskRequest.EnvEntry
}
var file_cronicle_proto_depIdxs = []int32{
	13, // 0: cronicle.RegisterNodeRequest.resources:type_name -> cronicle.NodeResources
	13, // 1: cronicle.HeartbeatRequest.resources:type_name -> cronicle.NodeResources
	0,  // 2: cronicle.TaskRequest.type:type_name -> cronicle.TaskType
	15, // 3: cronicle.TaskRequest.env:type_name -> cronicle.TaskRequest.EnvEntry
	14, // 4: cronicle.TaskResult.resource_usage:type_name -> cronicle.ResourceUsage
	1,  // 5: cronicle.CronicleService.RegisterNode:input_type -> cronicle.RegisterNodeRequest
	3,  // 6: cronicle.CronicleService.Heartbeat:input_type -> cronicle.HeartbeatRequest
	5,  // 7: cronicle.CronicleService.UnregisterNode:input_type -> cronicle.UnregisterNodeRequest
	7,  // 8: cronicle.CronicleService.SubmitTask:input_type -> cronicle.TaskRequest
	9,  // 9: cronicle.CronicleService.ReportTaskResult:input_type -> cronicle.TaskResult
	11, // 10: cronicle.CronicleService.AbortTask:input_type -> cronicle.AbortTaskRequest
	2,  // 11: cronicle.CronicleService.RegisterNode:output_type -> cronicle.RegisterNodeResponse
	4,  // 12: cronicle.CronicleService.Heartbeat:output_type -> cronicle.HeartbeatResponse
	6,  // 13: cronicle.CronicleService.UnregisterNode:output_type -> cronicle.UnregisterNodeResponse
	8,  // 14: cronicle.CronicleService.SubmitTask:output_type -> cronicle.TaskResponse
	10, // 15: cronicle.CronicleService.ReportTaskResult:output_type -> cronicle.TaskResultAck
	12, // 16: cronicle.CronicleService.AbortTask:output_type -> cronicle.AbortTaskResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_cronicle_proto_init() }
func file_cronicle_proto_init() {
	if File_cronicle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cronicle_proto_rawDesc), len(file_cronicle_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cronicle_proto_goTypes,
		DependencyIndexes: file_cronicle_proto_depIdxs,
		EnumInfos:         file_cronicle_proto_enumTypes,
		MessageInfos:      file_cronicle_proto_msgTypes,
	}.Build()
	File_cronicle_proto = out.File
	file_cronicle_proto_goTypes = nil
	file_cronicle_proto_depIdxs = nil
}
